import * as path from 'path';
import {
  ECODE_COMPONENT_ENTRIES,
  type EcodeComponentEntry,
} from '../language/componentKnowledge';
import type { IndexedEcodeComponentCall } from '../language/WorkspaceComponentRegistry';
import {
  ECODE_API_ENTRIES,
  ECODE_API_OBJECTS,
  type EcodeApiEntry,
} from '../language/knowledge';
import {
  getApiNestedSchemas,
  getComponentNestedSchemas,
  type NestedProperty,
  type NestedSchema,
} from '../language/nestedKnowledge';

const GENERATED_HEADER = [
  '// Generated by Ecode Local. Do not edit this file directly.',
  '// Regenerate it with "Ecode: 刷新 AI Coding 支持".',
  '',
].join('\n');

export function generateGlobalDeclarations(): string {
  const nested = new NestedDeclarationWriter();
  const objectBlocks = ECODE_API_OBJECTS.map(info => {
    const entries = ECODE_API_ENTRIES.filter(entry => entry.object === info.object);
    const members = entries.map(entry => apiMember(entry, nested));
    return [
      jsDoc(info.description, info.officialUrl),
      `interface ${info.object}Api {`,
      ...members.map(member => indent(member)),
      '}',
      '',
    ].join('\n');
  });
  const globals = ECODE_API_OBJECTS.flatMap(info => [
    jsDoc(info.description, info.officialUrl),
    `declare const ${info.object}: ${info.object}Api;`,
  ]);
  const windowMembers = ECODE_API_OBJECTS
    .map(info => `  ${info.object}: ${info.object}Api;`);

  return ensureTrailingNewline([
    GENERATED_HEADER,
    ...nested.lines,
    ...objectBlocks,
    ...globals,
    '',
    'interface Window {',
    ...windowMembers,
    '}',
  ].join('\n'));
}

export function generateComponentDeclarations(): string {
  const nested = new NestedDeclarationWriter();
  const propInterfaces = ECODE_COMPONENT_ENTRIES.map(entry =>
    componentPropsInterface(entry, nested));
  const namespaces = ['ecCom', 'antd'] as const;
  const namespaceBlocks = namespaces.map(namespace => {
    const entries = ECODE_COMPONENT_ENTRIES
      .filter(entry => entry.namespace === namespace);
    const members = entries.map(entry =>
      `  readonly ${quoteProperty(entry.name)}: EcodeAiComponent<${componentPropsName(entry)}>;`);
    const exports = entries.map(entry =>
      `  export const ${entry.name}: EcodeAiComponent<${componentPropsName(entry)}>;`);
    return [
      `interface ${pascalCase(namespace)}ComponentLibrary {`,
      ...members,
      '}',
      '',
      `declare const ${namespace}: ${pascalCase(namespace)}ComponentLibrary;`,
      '',
      `declare module '${namespace}' {`,
      ...exports,
      '}',
      '',
    ].join('\n');
  });

  return ensureTrailingNewline([
    GENERATED_HEADER,
    'interface EcodeAiComponent<Props = Record<string, unknown>> {',
    '  (props: Props): unknown;',
    '}',
    '',
    ...nested.lines,
    ...propInterfaces,
    ...namespaceBlocks,
    'interface Window {',
    '  ecCom: EcComComponentLibrary;',
    '  antd: AntdComponentLibrary;',
    '}',
  ].join('\n'));
}

export function generateAiGuide(): string {
  return ensureTrailingNewline([
    '# Ecode AI Coding 指南',
    '',
    '本目录由 Ecode Local 自动生成，用于让 AI 编码工具理解 Ecode 运行时 API、组件和项目内组件注册关系。',
    '',
    '## 工作区约定',
    '',
    '- `ecode/` 是唯一的 Ecode 源码目录，远端拉取和推送只作用于该目录。',
    '- `.ecode-ai/` 是 AI 支持资料目录，不属于 Ecode 源码，禁止同步到远端。',
    '- 不要假设 Ecode 全局对象来自 npm 包；`WfForm`、`ModeForm`、`ModeList`、`ecodeSDK`、`ecCom` 和 `antd` 由平台运行时提供。',
    '- 平台 JavaScript 编译环境以 Babel 7.5.5 兼容能力为准，生成代码时避免依赖过新的语法和运行时 API。',
    '',
    '## 编码前应读取',
    '',
    '- `ecode-globals.d.ts`：全局 API、签名、参数及嵌套参数。',
    '- `ecode-components.d.ts`：PC 组件、props 及嵌套 props。',
    '- `workspace-components.md`：当前项目的 `ecodeSDK.setCom/getCom` 组件关系。',
    '',
    '## 生成代码规则',
    '',
    '1. 调用 API 前核对对象、方法名、参数顺序、可选参数和返回值。',
    '2. 对 `WeaBrowser.tabs`、`WeaTable.columns` 等对象或数组参数，使用声明中的二级结构。',
    '3. 使用 `ecodeSDK.getCom(appId, name)` 前，优先在工作区组件表中确认对应 `setCom` 定义。',
    '4. 类型为 `unknown` 表示官方资料不足，必须从现有调用或运行时行为继续确认，不应擅自猜测。',
    '5. 不修改 `.ecode-ai/` 中的生成文件；知识变化后使用扩展命令重新生成。',
    '',
    '## 常见示例',
    '',
    '```javascript',
    'const fieldId = WfForm.convertFieldNameToId("field_name");',
    'const value = WfForm.getFieldValue(fieldId);',
    '',
    'const Widget = ecodeSDK.getCom("appId", "Widget");',
    '```',
  ].join('\n'));
}

export function generateWorkspaceComponents(
  workspaceRoot: string,
  calls: readonly IndexedEcodeComponentCall[],
): string {
  const groups = new Map<string, IndexedEcodeComponentCall[]>();
  for (const call of calls) {
    const key = `${call.appId}\0${call.name}`;
    const group = groups.get(key) ?? [];
    group.push(call);
    groups.set(key, group);
  }
  const sections = [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([, group]) => {
      const first = group[0];
      const definitions = group.filter(call => call.kind === 'definition');
      const references = group.filter(call => call.kind === 'reference');
      return [
        `## ${escapeMarkdown(first.name)}`,
        '',
        `- appId: \`${escapeCode(first.appId)}\``,
        `- 组件名: \`${escapeCode(first.name)}\``,
        `- 定义: ${locationList(workspaceRoot, definitions)}`,
        `- 引用: ${locationList(workspaceRoot, references)}`,
        '',
      ];
    });
  return ensureTrailingNewline([
    '# Ecode 工作区组件',
    '',
    '由 Ecode Local 从 `ecode/` 内的 `ecodeSDK.setCom/getCom` 调用生成。',
    '',
    ...(sections.length > 0
      ? sections
      : ['当前 `ecode/` 源码中尚未发现静态组件注册或引用。', '']),
  ].join('\n'));
}

export function normalizeType(rawType: string): string {
  const value = rawType
    .replace(/\s+/g, ' ')
    .trim();
  if (!value) {
    return 'unknown';
  }
  if (/^(any|unknow|未知)$/i.test(value)) {
    return 'unknown';
  }
  if (/^(string|number|boolean|void|never|null|undefined|unknown|Date)$/i.test(value)) {
    const lower = value.toLowerCase();
    return lower === 'date' ? 'Date' : lower;
  }
  if (/^(bool)$/i.test(value)) {
    return 'boolean';
  }
  if (/^(int|integer|float|double)$/i.test(value)) {
    return 'number';
  }
  if (/^(object|map|json)$/i.test(value)) {
    return 'Record<string, unknown>';
  }
  if (/^(array|list|集合|数组)$/i.test(value)) {
    return 'unknown[]';
  }
  if (/^(function|func|callback)$/i.test(value)) {
    return '(...args: unknown[]) => unknown';
  }
  if (/^function\s*\(([^)]*)\)$/i.test(value)) {
    const match = /^function\s*\(([^)]*)\)$/i.exec(value);
    const names = (match?.[1] ?? '')
      .split(',')
      .map(item => item.trim())
      .filter(Boolean)
      .map((item, index) => `${safeIdentifier(item, `arg${index + 1}`)}: unknown`);
    return `(${names.join(', ')}) => unknown`;
  }
  if (value.includes('=>')) {
    return /^\(\s*\)\s*=>\s*void$/i.test(value)
      ? '() => void'
      : '(...args: unknown[]) => unknown';
  }
  if (/\b(React|Element|Node|组件)\b/i.test(value)) {
    return 'unknown';
  }
  const arrayMatch = /^(?:Array|array)\s*<(.+)>$/i.exec(value);
  if (arrayMatch) {
    return `Array<${normalizeType(arrayMatch[1])}>`;
  }
  const suffixArray = /^(.+)\[\]$/.exec(value);
  if (suffixArray) {
    return `${parenthesizeUnion(normalizeType(suffixArray[1]))}[]`;
  }
  const unionParts = value.split(/\s*(?:\||\bor\b)\s*/i);
  if (unionParts.length > 1) {
    const normalized = [...new Set(unionParts.map(normalizeType))];
    return normalized.includes('unknown')
      ? 'unknown'
      : normalized.map(parenthesizeFunction).join(' | ');
  }
  if (/^(['"]).*\1$/.test(value) || /^-?\d+(?:\.\d+)?$/.test(value)) {
    return value;
  }
  return 'unknown';
}

class NestedDeclarationWriter {
  readonly lines: string[] = [];
  private readonly names = new Set<string>();

  typeForSchema(name: string, schema: NestedSchema): string {
    if (schema.itemProperties) {
      const itemName = `${name}Item`;
      return `${this.interfaceForProperties(itemName, schema.itemProperties)}[]`;
    }
    if (schema.properties) {
      return this.interfaceForProperties(name, schema.properties);
    }
    return 'Record<string, unknown>';
  }

  private interfaceForProperties(
    name: string,
    properties: readonly NestedProperty[],
  ): string {
    if (properties.length === 0) {
      return 'Record<string, unknown>';
    }
    if (!this.names.has(name)) {
      this.names.add(name);
      const members = properties.map(property => {
        let type = normalizeType(property.type);
        if (property.properties) {
          type = this.interfaceForProperties(
            `${name}${pascalCase(property.name)}`,
            property.properties,
          );
        } else if (property.itemProperties) {
          const itemType = this.interfaceForProperties(
            `${name}${pascalCase(property.name)}Item`,
            property.itemProperties,
          );
          type = `${itemType}[]`;
        }
        return [
          jsDoc(property.description),
          `${quoteProperty(property.name)}${property.required ? '' : '?'}: ${type};`,
        ].join('\n');
      });
      this.lines.push([
        `interface ${name} {`,
        ...members.map(member => indent(member)),
        '}',
        '',
      ].join('\n'));
    }
    return name;
  }
}

function apiMember(
  entry: EcodeApiEntry,
  nested: NestedDeclarationWriter,
): string {
  const parameterLines = entry.parameters.map(parameter =>
    `@param ${parameter.name} ${parameter.description} 原始类型：${parameter.type}`);
  const documentation = jsDoc(
    [entry.description, ...parameterLines].join('\n'),
    entry.officialUrl,
  );
  if (entry.kind === 'property') {
    const separator = entry.signature.indexOf(':');
    const rawType = separator >= 0 ? entry.signature.slice(separator + 1) : '';
    return `${documentation}\nreadonly ${quoteProperty(entry.name)}: ${normalizeType(rawType)};`;
  }
  const nestedTypes = new Map(
    getApiNestedSchemas(entry).map(item => [
      item.parameterName,
      nested.typeForSchema(
        `${pascalCase(entry.object)}${pascalCase(entry.name)}${pascalCase(item.parameterName)}`,
        item.schema,
      ),
    ]),
  );
  const parameters = entry.parameters.map((parameter, index) => {
    const hasRequiredAfter = entry.parameters
      .slice(index + 1)
      .some(candidate => candidate.required);
    const optional = !parameter.required && !hasRequiredAfter;
    let type = nestedTypes.get(parameter.name) ?? normalizeType(parameter.type);
    if (!parameter.required && hasRequiredAfter) {
      type = `${parenthesizeFunction(type)} | undefined`;
    }
    return `${safeIdentifier(parameter.name, `arg${index + 1}`)}${optional ? '?' : ''}: ${type}`;
  });
  return [
    documentation,
    `${quoteProperty(entry.name)}(${parameters.join(', ')}): ${methodReturnType(entry.signature)};`,
  ].join('\n');
}

function componentPropsInterface(
  entry: EcodeComponentEntry,
  nested: NestedDeclarationWriter,
): string {
  const nestedTypes = new Map(
    getComponentNestedSchemas(entry).map(item => [
      item.propName,
      nested.typeForSchema(
        `${componentPropsName(entry)}${pascalCase(item.propName)}`,
        item.schema,
      ),
    ]),
  );
  const members = entry.props.map(prop => [
    jsDoc([
      prop.description,
      prop.defaultValue ? `默认值：${prop.defaultValue}` : '',
      `原始类型：${prop.type}`,
    ].filter(Boolean).join('\n')),
    `${quoteProperty(prop.name)}${prop.required ? '' : '?'}: ${
      nestedTypes.get(prop.name) ?? normalizeType(prop.type)
    };`,
  ].join('\n'));
  return [
    jsDoc(`${entry.title}\n${entry.description}`, entry.officialUrl),
    `interface ${componentPropsName(entry)} {`,
    ...members.map(member => indent(member)),
    '}',
    '',
  ].join('\n');
}

function componentPropsName(entry: EcodeComponentEntry): string {
  return `${pascalCase(entry.namespace)}${pascalCase(entry.name)}Props`;
}

function methodReturnType(signature: string): string {
  const match = /\)\s*:\s*(.+)$/.exec(signature);
  return normalizeType(match?.[1] ?? '');
}

function locationList(
  workspaceRoot: string,
  calls: readonly IndexedEcodeComponentCall[],
): string {
  if (calls.length === 0) {
    return '无';
  }
  return calls.map(call => {
    const relative = path.relative(workspaceRoot, call.uri.fsPath)
      .split(path.sep)
      .join('/');
    return `\`${escapeCode(relative)}:${call.range.start.line + 1}\``;
  }).join('、');
}

function jsDoc(description: string, url?: string): string {
  const lines = description
    .replace(/\*\//g, '*\\/')
    .split(/\r?\n/);
  if (url) {
    lines.push(`来源：${url}`);
  }
  return ['/**', ...lines.map(line => ` * ${line}`), ' */'].join('\n');
}

function indent(value: string): string {
  return value.split('\n').map(line => `  ${line}`).join('\n');
}

function pascalCase(value: string): string {
  const result = value
    .replace(/[^A-Za-z0-9_$]+(.)?/g, (_match, next: string | undefined) =>
      next?.toUpperCase() ?? '')
    .replace(/^[a-z]/, character => character.toUpperCase());
  return /^[A-Za-z_$]/.test(result) ? result : `Ecode${result}`;
}

function quoteProperty(value: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(value)
    ? value
    : JSON.stringify(value);
}

function safeIdentifier(value: string, fallback: string): string {
  const cleaned = value.replace(/^\.\.\./, '');
  return /^[A-Za-z_$][\w$]*$/.test(cleaned) ? cleaned : fallback;
}

function parenthesizeUnion(type: string): string {
  return type.includes('|') ? `(${type})` : type;
}

function parenthesizeFunction(type: string): string {
  return type.includes('=>') ? `(${type})` : type;
}

function escapeMarkdown(value: string): string {
  return value.replace(/([\\`*_{}[\]()#+\-.!])/g, '\\$1');
}

function escapeCode(value: string): string {
  return value.replace(/`/g, '\\`');
}

function ensureTrailingNewline(value: string): string {
  return `${value.replace(/\s+$/, '')}\n`;
}
